apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-eta-deploy
  labels:
    app: insurance-eta-app
spec:
  replicas: 2                                                                                         
  selector:
    matchLabels:
      app: insurance-eta-app
  template:
    metadata:
      labels:
        app: insurance-eta-app
    spec:
      containers:
      - name: healthcare-eta-container
        image: whitehouse23/insurance-eta-app
        ports:
        - containerPort: 8082  # Changed from 8082 to 8083
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-eta-np-service
  labels:
    app: insurance-eta-app
spec:
  selector:
    app: insurance-eta-app
  type: NodePort
  ports:
  - nodePort: 32031  # Changed from 31030 to 32030
    port: 8082       # Changed from 8082 to 8083
    targetPort: 8082 # Changed from 8082 to 8083
